version: '3.8'

services:
  ## ────── MongoDB ─────────────────────────────────────────
  mongodb:
    image: mongo:latest               # официальный образ MongoDB
    container_name: namaz_mongo       # читаемое имя
    restart: unless-stopped           # авто-перезапуск при падениях
    ports:
      - "27017:27017"                 # маппим порт 27017
    volumes:
      - ./data/db:/data/db            # данные вне контейнера

  ## ────── FastAPI приложение ─────────────────────────────
  app:
    build: .                          # Dockerfile в текущей папке
    container_name: namaz_app         # читаемое имя
    restart: unless-stopped           # авто-перезапуск
    ports:
      - "8000:8000"                   # порт uvicorn
    depends_on:
      - mongodb                       # ждём MongoDB
    environment:
      - MONGO_URI=mongodb://mongodb:27017/namaz_db  # подключаемся к сервису mongodb
      - PORT=8000
    volumes:
      - .:/app                        # монтируем код внутрь контейнера
